version: '3.9'
services:
  app:
    container_name: app
    build: ./app
    volumes:
      - ./app:/usr/local/bin/app
    ports:
      - ${WEB_APP_PORT}:3000
    networks:
      - fullstack
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14.4-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  db_volume

networks:
  fullstack:
    driver: bridge