version: '3.9'
services:
  open-tester-api:
    container_name: open-tester-api
    build: api
    volumes:
      - ./api:/usr/src/app
    ports:
      - ${WEB_APP_PORT}:8081
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - WEB_APP_PORT=${WEB_APP_PORT}
    networks:
      - fullstack
    depends_on:
      - db

  open-tester-front:
    container_name: open-tester-front
    build: front
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"
    depends_on:
      - api

  open-tester-db:
    container_name: db
    image: postgres:alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge